cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"
members = [
    "malefic",
    "malefic-modules",
    "malefic-helper",
    "malefic-trait",
    "malefic-mutant",
    "malefic-core",
    "malefic-prelude",
    "malefic-proto",
    "malefic-pulse"
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
panic_unwind = false
panic = "abort"
opt-level = "z"
debug-assertions = false
strip = true
codegen-units = 1
incremental = false
rustflags = [
    "-Z", "trim-diagnostic-paths",
    "--cfg", "hide_path",
]

[profile.release-lto]
inherits = "release"
lto = true