[package]
name = "malefic-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
lazy_static = { version = "1.4", features = ["spin_no_std"]}
serde_yaml = "0.9"
serde_json = "1.0"
jsonschema = "0.18.0"
toml_edit = "0.22.15"
